enableTelemetry: false

httpTimeout: 600000

networkConcurrency: 1

nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  hydro:
    npmRegistryServer: "https://registry.npmmirror.com/"

preferInteractive: true

preferReuse: true

tsEnableAutoTypes: true
